#define fishing_bg_offset	0	// (null)
#define fishing_wait_00	1	// ウェイト
#define fishing_pick_00	2	// つんつん
#define fishing_bite_00	3	// 噛み付き
#define fishing_just_00	4	// ジャスト
#define fishing_miss_00	5	// あたりそこね
#define fishing_through_00	6	// 見逃し
#define fishing_out_00	7	// ムダ入力
#define fishing_wait_01	8	// ウェイト
#define fishing_pick_01	9	// つんつん
#define fishing_rest_01	10	// 休符
#define fishing_bite_01	11	// 噛み付き
#define fishing_just_01	12	// ジャスト
#define fishing_miss_01	13	// あたりそこね
#define fishing_through_01	14	// 見逃し
#define fishing_out_01	15	// ムダ入力
#define fishing_wait_02	16	// ウェイト
#define fishing_wait_02b	17	// ウェイト(,ミマチ横取り)
#define fishing_pick_02	18	// つんつん
#define fishing_pick_up_02	19	// つんつん
#define fishing_pick_down_02	20	// つんつん
#define fishing_rest_02	21	// 休符
#define fishing_bite_02	22	// 噛み付き
#define fishing_just_02	23	// ジャスト
#define fishing_miss_02	24	// あたりそこね
#define fishing_through_02	25	// 見逃し
#define fishing_out_02	26	// ムダ入力
#define fishing_girl	27	// (null)
#define fishing_girl_just_loop	28	// ジャスト
#define fishing_girl_just	29	// (null)
#define fishing_girl_through	30	// 見逃し
#define fishing_girl_miss	31	// あたりそこね
#define fishing_bubble	32	// (null)
#define fishing_test00	33	// ※大澤さんmade
#define fishing_test01	34	// ※大澤さんmade
#define fishing_test02	35	// ※大澤さんmade
#define fishing_test03	36	// ※大澤さんmade
#define fishing_test04	37	// ※大澤さんmade
