#define fishing_bg_bg_00	0	// îwåi_00
#define fishing_bg_bg_01	1	// îwåi_01
#define fishing_bg_bg_02	2	// îwåi_02
#define fishing_bg_fish_00_loop	3	// 7ÉtÉåãõÇ®ÇÊÇÆ
#define fishing_bg_fish_00_go_R	4	// â°Ç…ì¶Ç∞ÇÈ
#define fishing_bg_fish_00_go_D	5	// â∫Ç…ì¶Ç∞ÇÈ
#define fishing_bg_fish_00_go_U	6	// è„Ç…ì¶Ç∞ÇÈ
#define fishing_bg_fish_00_loop_S	7	// 7ÉtÉåãõÇ®ÇÊÇÆ(è¨)
#define fishing_bg_fish_00_go_RS	8	// â°Ç…ì¶Ç∞ÇÈ(è¨)
#define fishing_bg_fish_00_go_DS	9	// â∫Ç…ì¶Ç∞ÇÈÅiè¨Åj
#define fishing_bg_fish_00_go_US	10	// è„Ç…ì¶Ç∞ÇÈÅiè¨Åj
#define fishing_bg_fish_01_loop	11	// ÇUÉtÉåãõÇ®ÇÊÇÆ
#define fishing_bg_fish_01_go_R	12	// â°Ç…ì¶Ç∞ÇÈ
#define fishing_bg_fish_01_go_D	13	// â∫Ç…ì¶Ç∞ÇÈ
#define fishing_bg_fish_01_go_U	14	// è„Ç…ì¶Ç∞ÇÈ
#define fishing_bg_fish_01_loop_S	15	// ÇUÉtÉåãõÇ®ÇÊÇÆ(è¨)
#define fishing_bg_fish_01_go_RS	16	// â°Ç…ì¶Ç∞ÇÈ(è¨)
#define fishing_bg_fish_01_go_DS	17	// â∫Ç…ì¶Ç∞ÇÈÅiè¨Åj
#define fishing_bg_fish_01_go_US	18	// è„Ç…ì¶Ç∞ÇÈÅiè¨Åj
#define fishing_bg_fish_02_loop	19	// 10ÉtÉåÇ®ÇÊÇÆ
#define fishing_bg_fish_02_go_R	20	// â°Ç…ì¶Ç∞ÇÈ
#define fishing_bg_fish_02_go_D	21	// â∫Ç…ì¶Ç∞ÇÈ
#define fishing_bg_fish_02_go_U	22	// è„Ç…ì¶Ç∞ÇÈ
#define fishing_bg_fish_02_loop_S	23	// 10ÉtÉåÇ®ÇÊÇÆ(è¨)
#define fishing_bg_fish_02_go_RS	24	// â°Ç…ì¶Ç∞ÇÈ(è¨)
#define fishing_bg_fish_02_go_DS	25	// â∫Ç…ì¶Ç∞ÇÈÅiè¨Åj
#define fishing_bg_fish_02_go_US	26	// è„Ç…ì¶Ç∞ÇÈ(è¨)
#define fishing_bg__bg_00	27	// îwåi_00
#define fishing_bg__bg_01	28	// îwåi_01
#define fishing_bg__bg_02	29	// îwåi_02
#define fishing_bg_CellAnim0	30	// (null)
#define fishing_bg_CellAnim1	31	// (null)
